---
- hosts: vb

  vars_files:
    - ./vars/deploy_vault.yml
    - ./vars/deploy_vars.yml

  vars_prompt:
    - name: git_branch
      prompt: 'Enter a branch to deploy'
      default: master
      private: no

  vars:
    ansistrano_deploy_to: "/usr/share/nginx/symfony"
    ansistrano_deploy_via: git
    ansistrano_git_repo: "git@192.168.56.2:root/symfony.git"
    ansistrano_git_branch: "{{ git_branch }}"
    ansistrano_git_identity_key_path: ~/.ssh/id_rsa
    ansistrano_before_setup_tasks_file: "{{ playbook_dir }}/deploy/before-setup.yml"
    ansistrano_after_symlink_shared_tasks_file: "{{ playbook_dir }}/deploy/after-symlink-shared.yml"
    release_console_path: "{{ ansistrano_release_path.stdout }}/bin/console"
#    ansistrano_shared_paths:
#      - var/logs
    release_var_path: "{{ ansistrano_release_path.stdout }}/var"

  environment:
    SYMFONY_ENV: prod

  roles:
    - ansistrano.deploy
