version: 2
jobs:
  build_and_test:
    working_directory: ~/project
    docker:
      - image: php:7.2
      - image: mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
    steps:
      # Installation
      - run:
          name: Install System Packages
          command: apt-get update && apt-get -y install git unzip zlib1g-dev
      - run:
          name: Install PHP Extensions
          command: docker-php-ext-install pdo pdo_mysql zip
      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
            php -r "if (hash_file('sha384', 'composer-setup.php') === '756890a4488ce9024fc62c56153228907f1545c228516cbf63f885e036d37e9a59d27d63f46af1d4d07ee0f76181c7d3') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
            php composer-setup.php && \
            php -r "unlink('composer-setup.php');" && \
            chmod +x ./composer.phar && \
            mv ./composer.phar /usr/local/bin/composer

      # Dependencies
      - checkout
      - restore_cache:
          key: project-{{ .Branch }}-{{ checksum "./composer.lock" }}-v1
      - run: composer install --prefer-dist --no-interaction
      # Force pulling Simple PHPUnit dependencies to be able to cache them as well
      - run: ./bin/phpunit --version
      - save_cache:
          key: project-{{ .Branch }}-{{ checksum "./composer.lock" }}-v1
          paths:
            - '/root/.composer/cache'
            - './vendor'

      # Database
      - run: ./bin/console doctrine:database:create --env=test
      - run: ./bin/console doctrine:schema:create --env=test
#      - run: ./bin/console hautelook_alice:doctrine:fixtures:load --no-interaction

      # To use server:start we need to install pcntl extension
      - run:
          name: Run web server in background
          command: php -S 127.0.0.1:8000 -t public
          background: true

      # Testing
#      - run: ./bin/console lint:yaml app/config
#      - run: ./bin/console lint:twig app/Resources
      - run: ./bin/phpunit

  deploy:
    working_directory: ~/project
    docker:
      - image: willhallonline/ansible
        environment:
          ANSIBLE_HOST_KEY_CHECKING: no
    steps:
      # Installation
      - run:
          name: Install System Packages
          command: pip install --upgrade pip && pip install ansible

      # Dependencies
      - checkout
      - restore_cache:
          key: project-{{ .Branch }}-{{ checksum "./ansible/requirements.yml" }}-v1
      - run: ansible-galaxy install -r ansible/requirements.yml
      - save_cache:
          key: project-{{ .Branch }}-{{ checksum "./ansible/requirements.yml" }}-v1
          paths:
            - '/root/.ansible/roles'

      # Deploy
      - run: echo $ANSIBLE_VAULT_PASS > ./ansible/.vault-pass.txt
      - run: ansible-playbook ansible/deploy.yml -i ansible/hosts.ini -e "git_branch=main" --vault-password-file=./ansible/.vault-pass.txt
      - run: rm ./ansible/.vault-pass.txt

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
