---
- name: Check that the git_identity_key exists
  stat:
    path: "{{ ansistrano_deploy_to }}/git_identity_key"
  register: stat_result

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: "{{ ansistrano_deploy_to }}/git_identity_key"
#    owner: "{{ ansible_user }}"
#    group: "{{ ansible_user }}"
    mode: '0644'
#    force: yes
    state: touch
  when: stat_result.stat.exists

- debug:
    var: stat_result
